"""remove_2fa_fields_from_users_table

Revision ID: 954ed4a764a1
Revises: ecce17ffc463
Create Date: 2025-09-19 18:04:19.535351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954ed4a764a1'
down_revision: Union[str, None] = 'ecce17ffc463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_2fa_enabled')
    op.drop_column('users', 'otp_secret')
    op.drop_column('users', 'last_otp_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_otp_verified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('otp_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
