"""Make hashed_password nullable

Revision ID: cfc72d1b0cfb
Revises: ecce17ffc463
Create Date: 2025-09-15 23:25:29.552040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc72d1b0cfb'
down_revision: Union[str, None] = 'ecce17ffc463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
