"""add last_otp_verified column to users table

Revision ID: ecce17ffc463
Revises: f425e2befc06
Create Date: 2025-09-15 23:06:32.972120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecce17ffc463'
down_revision: Union[str, None] = 'f425e2befc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_otp_verified', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_otp_verified')
    # ### end Alembic commands ###
